# Site settings
title: This is where my witty title will go
email: federicogmenozzi@gmail.com
description: > # This means to ignore newlines until "baseurl:"
    Posts that make you go "Huh. Cool."
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: fmenozzi

# Build settings
markdown: kramdown
